// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Name ユーザー名
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code エラーコード
	Code *int `json:"code,omitempty"`

	// Detail エラーメッセージ
	Detail *string `json:"detail,omitempty"`
}

// User defines model for User.
type User struct {
	// Email メールアドレス
	Email openapi_types.Email `json:"email"`

	// Id Firebase UID
	Id string `json:"id"`

	// Name ユーザー名
	Name string `json:"name"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// ユーザー作成
	// (POST /v1/users)
	CreateUser(ctx echo.Context) error
	// 自分のユーザー情報取得
	// (GET /v1/users/me)
	GetMe(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/health", wrapper.HealthCheck)
	router.POST(baseURL+"/v1/users", wrapper.CreateUser)
	router.GET(baseURL+"/v1/users/me", wrapper.GetMe)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SW32/cRBDH/5XTwhtWfGmCVPxEk1A48atqyVN0D3u+Sc6Nveuu11GvlR9sk3IhCUQV",
	"oq1UCShVCBdKCBUoUa/0j9n6evkv0K7N3Tm+XAotytOdvZ6Z78x8dnZvIpM6LiVAuIeMm4iB51LigXqY",
	"wfXLcM0Hj8snkxIORP3FrmtbJuYWJbrLaM0G562rHiVyzTMb4GD5700Gi8hAb+iDEHq66unvMUbZ5SwY",
	"CoJAQ3XwTGa50ikykIjbItoT0Y6IDkXcEuHG84PN7qMfUaChWUoWbcs8K1VPRdyRqsKN7p0HItxNHt1N",
	"7u+I8J6I1qW8CuHACLavAFsBpnyegdLoDykz3hJxJ7m1ehTvyFrGP4u4IzV+QvlF6pP6mZewt70uwoci",
	"XBfRmgjbIvxcypsn2OcNyqwbcAYSe+3N3k5HhBvJs9XedojkF5mx9D3LAHOY94AN7Q6XURcYt9KdQ7AD",
	"8vd46tsq7z9lT7Y2kYbgOnZcG5CBkv39F9/8ljxsH8VfIQ3xpivfepxZZEkJYHDNt5gsx0Lqvtr/itau",
	"gsll3fKpFWSZtD5K1j9giOixYmZtIMAiHJaAIVUjji17nHn8g4hjET1Rrg5GZlFQLMtYFArO6FAyQkfE",
	"uyJ6IOI1Ef8iosNcGX0P2LvZ44RJHaShRcoczJGROS2o0pBVL4a6aDGoYQ9K85W5XARcMyfPTV1v3hjl",
	"6X/uu1WXtlkaJ0AgWQXTZxZvXpHMZqMcMAN2weeNMalW5kqf0WUgKMNduq0pw4GyBuduumcsskiLzi5N",
	"E96YoqTk+jXbMksXLlWkscVVtv3V9PUKMC81m5woT5RlBakLBLsWMtDURHliCmnIxbyhctAbgO00gSVQ",
	"m04ioyZBpY4M9IFanm2AuYy0/El2rlweM0aK4yNPo8cx91Mu+32jyy/Dd3G2fPphrkXIWKhqyPMdB7Om",
	"QuWuwvtQxKGIflL7aU9GwkueJCArQVX60Fcmdcm7UubSdA6Nbm060boHLRE+G6ZRRLfnZkS4++Lek6ON",
	"37MjTDtW18G8QymO4PEZWm/+q4qOG8jFgRrkyefMh6DQ0snXJkDlNvKsGpTq+dP73dZWt7WVfPmdBHU6",
	"RWqU275OfegGpUwmTzfJHX3K6J3Tjfo3okBDb7+MsFF3FMXlEInHcx/CMMUuT6Gejr5sa47jUN7npOs9",
	"ET/OTv6hYN14Nfl+X0S3k6+/Tf66cwKU7wP/GF51m78qE6nUVOcwGf+pzdOnG/Vvba+vzb0v2knrlgh/",
	"PSmvUV3PD7D86bJQDeREUwE9tZqv30fUxHapDitgU9cBwkvpt0hDPrOzE8bQdVt+16AeN86Xz5dRUA3+",
	"DgAA///w94gtrAwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
